import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Link, Typography } from '../components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography variant='h1' label='MUI+Storybook Demo' />
        <Link href='/profile'>
          <Button sx={{ mt: 6 }} variant='contained' label="To Demo Page" />
        </Link>
      </main >
    </div >
  )
}

export default Home
